### PR TITLE
Add requirements to get USB connection working on Linux

### PR DESCRIPTION
**Pull request by joelnb**
Fix some errors which meant I was unable to get the USB config updates working in Linux. I have not tried these on Windows or Mac at this point but I believe they should work there.

I also added some documentation of how to get things working on Linux - I needed a Udev rule to allow the connection to work & also I had previously not seen specific instructions for how to get the app working on Linux.

### CODE REVIEW

**Comment by joelnb** [comment]
With the latest commit I am also able to save files fine.

**Comment by joelnb** [comment]
Thanks for looking! I am just doing some improvements on what I have done here - I am going to also do some instructions about installing the udev rule so that other people will know how to get it working. I'll take the Draft status off this PR when I'm done.

**Comment by joelnb** [comment]
I am happy with this now & seems to work correctly. I went through & removed all the `print` statements I had in this PR - instead I created https://github.com/dekuNukem/duckyPad/pull/62 where I added some simple logging setup which I hope doesn't conflict with anything. I wanted to keep it separate from these changes but I had to base it off the changes I made here in order to test it so there is no point looking at that PR until this one is merged.

**Comment by dekuNukem** [comment]
I took a look at the code and it was pretty good! I'm a bit busy this week and haven't had a chance to try it out on linux yet, but I'm planning to do it this weekend on a Ubuntu machine. Thank you very much for the contribution!

**Comment by joelnb** [comment]
No rush. I really like the ability to manage the profiles over USB so I'm happy to help if I can. Appreciate your efforts to make the duckyPad a reality!

**Pull request merged**
